import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import HeroSection from '@/components/HeroSection'
import AirdropPopUp from '@/components/AirdropPopUp'
import TrendingSection from '@/components/TrendingSection'

export default function Home() {
  return (
    <section className={styles.container}>
      <Head>
        <title>Blur: NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <section className={styles.main}>
          <Header />
          <HeroSection />
          <AirdropPopUp />
        </section>
        <TrendingSection />
      </section>
    </section>
  )
}
